// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWXlRWA30-RAosgHNbp-NwP9CrhgLQXr8',
    appId: '1:509419060164:web:c6ae37a2e6491490d9c291',
    messagingSenderId: '509419060164',
    projectId: 'study-planner-ufscar',
    authDomain: 'study-planner-ufscar.firebaseapp.com',
    storageBucket: 'study-planner-ufscar.firebasestorage.app',
    databaseURL: 'https://study-planner-ufscar-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-17vT0cRxk1mJ_K8ie3lswKutcQh3WaQ',
    appId: '1:509419060164:android:9111b15e97e124f4d9c291',
    messagingSenderId: '509419060164',
    projectId: 'study-planner-ufscar',
    storageBucket: 'study-planner-ufscar.firebasestorage.app',
    databaseURL: 'https://study-planner-ufscar-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo9YwFyL5VHta4BqLARXqwrRm_CdaLDNM',
    appId: '1:509419060164:ios:9fa4b873c223bb66d9c291',
    messagingSenderId: '509419060164',
    projectId: 'study-planner-ufscar',
    storageBucket: 'study-planner-ufscar.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
    databaseURL: 'https://study-planner-ufscar-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo9YwFyL5VHta4BqLARXqwrRm_CdaLDNM',
    appId: '1:509419060164:ios:9fa4b873c223bb66d9c291',
    messagingSenderId: '509419060164',
    projectId: 'study-planner-ufscar',
    storageBucket: 'study-planner-ufscar.firebasestorage.app',
    iosBundleId: 'com.example.studyPlanner',
    databaseURL: 'https://study-planner-ufscar-default-rtdb.firebaseio.com'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWXlRWA30-RAosgHNbp-NwP9CrhgLQXr8',
    appId: '1:509419060164:web:7ca891169245d8f7d9c291',
    messagingSenderId: '509419060164',
    projectId: 'study-planner-ufscar',
    authDomain: 'study-planner-ufscar.firebaseapp.com',
    storageBucket: 'study-planner-ufscar.firebasestorage.app',
    databaseURL: 'https://study-planner-ufscar-default-rtdb.firebaseio.com'
  );
}
